# Generated by Django 4.0.6 on 2022-07-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Padre',
            new_name='Familia',
        ),
        migrations.DeleteModel(
            name='Hermana',
        ),
        migrations.DeleteModel(
            name='Madre',
        ),
    ]
