# Generated by Django 4.0.6 on 2022-07-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0002_rename_padre_familia_delete_hermana_delete_madre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='dni',
            new_name='edad',
        ),
    ]
