# Generated by Django 4.0.6 on 2022-07-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_rename_dni_familia_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha_nac',
            field=models.DateField(),
        ),
    ]
